//===- cal-opt.cpp ---------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "mlir/IR/MLIRContext.h"
#include "mlir/InitAllDialects.h"
#include "mlir/InitAllPasses.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Tools/mlir-opt/MlirOptMain.h"
#include "mlir/Transforms/Passes.h"

#include "Dialect/Cal/CalDialect.h"
#include "Dialect/Cal/CalPasses.h"
#include "Dialect/Fifo/FifoDialect.h"
#include "Dialect/Fifo/FifoPasses.h"

void registerLowerFifoToLLVMPipeline();

int main(int argc, char **argv) {
  mlir::registerAllPasses();
  mlir::cal::registerPasses();
  mlir::fifo::registerPasses();
  // TODO: Register cal passes here.

  mlir::DialectRegistry registry;
  registry.insert<mlir::cal::CalDialect, mlir::fifo::FifoDialect,
                  mlir::arith::ArithDialect, mlir::func::FuncDialect,
                  mlir::memref::MemRefDialect, mlir::index::IndexDialect,
                  mlir::LLVM::LLVMDialect, mlir::cf::ControlFlowDialect,
                  mlir::scf::SCFDialect, mlir::math::MathDialect,
                  mlir::func::FuncDialect>();
  // Add the following to include *all* MLIR Core dialects, or selectively
  // include what you need like above. You only need to register dialects that
  // will be *parsed* by the tool, not the one generated
  // registerAllDialects(registry);

  registerLowerFifoToLLVMPipeline();

  return mlir::asMainReturnCode(
      mlir::MlirOptMain(argc, argv, "Cal optimizer driver\n", registry));
}

/**
 * Registers the pipeline for lowering FIFO (and CAL) dialects to the LLVM dialect.
 *
 * This function uses MLIR's inline pass pipeline registration to register a pipeline
 * with the name "lower-cal-to-llvm" and a brief description. The pipeline first applies
 * FIFO/CAL-specific passes (e.g. lowering FIFO to memref and decomposing FIFO tuples) and
 * then applies a series of passes to lower the remaining standard MLIR dialects (SCF,
 * Arith, MemRef, Func, etc.) into their corresponding LLVM representations.
 *
 * For details on pass pipeline registration and instance-specific pass options, see:
 *   https://mlir.llvm.org/docs/PassManagement/#pass-pipeline-registration
 *   https://mlir.llvm.org/docs/PassManagement/#instance-specific-pass-options
 *
 * A similar example of an inline pipeline builder can be found in:
 *   llvm-project/mlir/lib/Dialect/Bufferization/Pipelines/BufferizationPipelines.cpp
 *
 * DISCLAIMER: This description has been generated by ChatGPT but verified by the code author.
 */
void registerLowerFifoToLLVMPipeline() {
  mlir::PassPipelineRegistration<>(
      "lower-cal-to-llvm",
      "Pipline lowering FIFO and CAL dialects to LLVM dialect.",
      [](mlir::OpPassManager &pm) {
        // 1. FIFO/CAL-specific lowering:
        //    - Lower FIFO operations to MemRef operations before decomposing FIFO tuples.
        pm.addPass(mlir::fifo::createLowerFifoToMemrefPass());
        pm.addPass(mlir::fifo::decomposeFifoTuples());
        pm.addPass(mlir::fifo::lowerFifoPrintToLLVM());

        // 2. Standard MLIR to LLVM lowering:
        //    The following passes lower various MLIR dialects to LLVM.
        //    (The ordering and combination of these passes follow similar pipelines
        //     as in the LLVM project, for example in TestLowertoLLVM.cpp.)

        // pm.addNestedPass<func::FuncOp>(createConvertVectorToSCFPass());
        // // Blanket-convert any remaining linalg ops to loops if any remain.
        // pm.addNestedPass<func::FuncOp>(createConvertLinalgToLoopsPass());
        // // Blanket-convert any remaining affine ops if any remain.
        // pm.addPass(createLowerAffinePass());
        // Convert SCF to CF (always needed).
        pm.addPass(mlir::createConvertSCFToCFPass());
        // Sprinkle some cleanups.
        pm.addPass(mlir::createCanonicalizerPass());
        pm.addPass(mlir::createCSEPass());
        // Convert vector to LLVM (always needed).
        // pm.addPass(createConvertVectorToLLVMPass(
        //     // TODO: add more options on a per-need basis.
        //     ConvertVectorToLLVMPassOptions{options.reassociateFPReductions}));
        // // Convert Math to LLVM (always needed).
        pm.addNestedPass<mlir::func::FuncOp>(
            mlir::createConvertMathToLLVMPass());
        // Expand complicated MemRef operations before lowering them.
        pm.addPass(mlir::memref::createExpandStridedMetadataPass());
        // // The expansion may create affine expressions. Get rid of them.
        // pm.addPass(createLowerAffinePass());
        // // Convert MemRef to LLVM (always needed).
        pm.addPass(mlir::createFinalizeMemRefToLLVMConversionPass());
        // // Convert Func to LLVM (always needed).
        pm.addPass(mlir::createConvertFuncToLLVMPass());
        // // Convert Arith to LLVM (always needed).
        pm.addPass(mlir::createArithToLLVMConversionPass());
        // // Convert CF to LLVM (always needed).
        pm.addPass(mlir::createConvertControlFlowToLLVMPass());
        // // Convert Index to LLVM (always needed).
        pm.addPass(mlir::createConvertIndexToLLVMPass());
        // // Convert remaining unrealized_casts (always needed).
        pm.addPass(mlir::createReconcileUnrealizedCastsPass());
      });
}
