#include "Conversion/CalLoweringPipelines/CalLoweringPipelines.h"

// MLIR Core
#include "mlir/IR/MLIRContext.h"
#include "mlir/InitAllDialects.h"
#include "mlir/InitAllExtensions.h"
#include "mlir/InitAllPasses.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Tools/mlir-opt/MlirOptMain.h"
#include "mlir/Transforms/Passes.h"

// MLIR Conversions
#include "mlir/Conversion/GPUToNVVM/GPUToNVVMPass.h"
#include "mlir/Conversion/UBToLLVM/UBToLLVM.h"

// MLIR Dialects and Transforms
#include "mlir/Dialect/Arith/Transforms/BufferDeallocationOpInterfaceImpl.h"
#include "mlir/Dialect/Arith/Transforms/BufferViewFlowOpInterfaceImpl.h"
#include "mlir/Dialect/Arith/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Pipelines/Passes.h"
#include "mlir/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/GPU/Pipelines/Passes.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/AllInterfaces.h"
#include "mlir/Dialect/SCF/Transforms/BufferDeallocationOpInterfaceImpl.h"
#include "mlir/Dialect/SCF/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Tensor/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/UB/IR/UBOps.h"

// MLIR LLVM Target Support
#include "mlir/Target/LLVMIR/Dialect/GPU/GPUToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Dialect/NVVM/NVVMToLLVMIRTranslation.h"

// Project-specific dialects
#include "Dialect/Cal/CalDialect.h"
#include "Dialect/Cal/CalPasses.h"
#include "Dialect/Fifo/BufferizableOpInterfaceImpl.h"
#include "Dialect/Fifo/FifoDialect.h"
#include "Dialect/Fifo/FifoPasses.h"

// Project-specific conversions and transformations
#include "Conversion/Passes.h"
#include "Transforms/Passes.h"

namespace mlir::cal {

void registerCalPipelines() {
  registerLowerCalToLLVMPipeline();
  registerLowerCalToLLVMWithStaticSchedulePipeline();
  registerLowerCalToLLVMWithGPUTensorsPipeline();
}

/**
 * Registers the pipeline for lowering FIFO and CAL dialects to the LLVM
 * dialect. This pipeline assumes all actors are not SDF or CSDF actors so makes
 * no assumptions about the static schedule of the actors.
 *
 * This function uses MLIR's inline pass pipeline registration to register a
 * pipeline with the name "lower-cal-to-llvm" and a brief description. The
 * pipeline first applies FIFO/CAL-specific passes (e.g. lowering FIFO to memref
 * and decomposing FIFO tuples) and then applies a series of passes to lower the
 * remaining standard MLIR dialects (SCF, Arith, MemRef, Func, etc.) into their
 * corresponding LLVM representations.
 *
 * For details on pass pipeline registration and instance-specific pass options,
 * see: https://mlir.llvm.org/docs/PassManagement/#pass-pipeline-registration
 *   https://mlir.llvm.org/docs/PassManagement/#instance-specific-pass-options
 *
 * A similar example of an inline pipeline builder can be found in:
 *   llvm-project/mlir/lib/Dialect/Bufferization/Pipelines/BufferizationPipelines.cpp
 *
 * DISCLAIMER: This description has been generated by ChatGPT but verified by
 * the code author.
 */
void registerLowerCalToLLVMPipeline() {
  mlir::PassPipelineRegistration<CalToLLVMWithMultithreadedFlagsOptions>(
      "lower-cal-to-llvm",
      "Pipeline lowering FIFO and CAL dialects to LLVM dialect.",
      [](mlir::OpPassManager &pm,
         const CalToLLVMWithMultithreadedFlagsOptions &options) {
        // 1. FIFO/CAL-specific lowering
        if (options.mergeSimpleCalActors)
          pm.addPass(mlir::cal::createMergeSimpleCalActors());

        pm.addPass(mlir::cal::insertCalPortPredicates());
        pm.addPass(mlir::cal::convertCalActionsToExecutionBodies());

        pm.addPass(mlir::cal::hoistCalStateOutOfActor());
        pm.addPass(mlir::createCanonicalizerPass());

        if (options.multithreadCalActors) {
          ConvertCalToFuncOptions funcOptions;
          funcOptions.actor_paritioning_mode = "multi-threaded";
          pm.addPass(mlir::createConvertCalToFunc(funcOptions));
        } else {
          pm.addPass(mlir::createConvertCalToFunc());
        }

        // We add this pass as we often get functions that are the same but with
        // different names.
        pm.addPass(mlir::func::createDuplicateFunctionEliminationPass());

        pm.addPass(mlir::createLowerCalStateToMemref());
        if (options.multithreadCalActors) {
          mlir::LowerFifoToMemrefPassOptions fifoOptions;
          fifoOptions.fifo_index_mode = std::string("spsc-lockfree");
          pm.addPass(mlir::createLowerFifoToMemrefPass(fifoOptions));
        } else {
          pm.addPass(mlir::createLowerFifoToMemrefPass());
        }
        pm.addPass(mlir::createDecomposeFifoTuples());
        pm.addPass(mlir::createFifoMemrefAtomicizePass());
        pm.addPass(mlir::fifo::createLowerFifoPrintToLLVM());

        mlir::bufferization::OneShotBufferizationOptions bufferizeOptions;
        bufferizeOptions.bufferizeFunctionBoundaries = true;
        pm.addPass(
            mlir::bufferization::createOneShotBufferizePass(bufferizeOptions));
        if (!options.disableHoistAllocs)
          pm.addPass(mlir::createHoistAllocsPass());
        pm.addPass(mlir::createCanonicalizerPass());

        // Async functions last after their region exists which the buffer
        // deallocation pass does not understand. Thus deallocation happens in
        // the wrong place. Just skipping it for now when using multithreading.
        // It does not create problems as memory is only allocated in the main
        // function.
        if (!options.multithreadCalActors) {
          pm.addPass(mlir::bufferization::createBufferDeallocationPass());
        }
        pm.addPass(mlir::createCanonicalizerPass());
        pm.addPass(mlir::createConvertLinalgToLoopsPass());
        pm.addPass(mlir::createCanonicalizerPass());

        if (options.multithreadCalActors) {
          pm.addPass(mlir::createAsyncToAsyncRuntimePass());
          pm.addPass(mlir::createAsyncRuntimeRefCountingPass());
          pm.addPass(mlir::createConvertAsyncToLLVMPass());
        }

        // 2. Standard MLIR to LLVM lowering:
        //    The following passes lower various MLIR dialects to LLVM.
        //    (The ordering and combination of these passes follow similar
        //    pipelines as in the LLVM project, for example in
        //    TestLowertoLLVM.cpp.)

        // Convert SCF to CF (always needed).
        pm.addPass(mlir::createConvertSCFToCFPass());
        // Sprinkle some cleanups.
        pm.addPass(mlir::createCanonicalizerPass());
        pm.addPass(mlir::createCSEPass());

        // Convert Math to LLVM (always needed).
        pm.addNestedPass<mlir::func::FuncOp>(
            mlir::createConvertMathToLLVMPass());
        // Expand complicated MemRef operations before lowering them.
        pm.addPass(mlir::memref::createExpandStridedMetadataPass());
        // The expansion may create affine expressions. Get rid of them.
        pm.addPass(mlir::createLowerAffinePass());
        // Convert MemRef to LLVM (always needed).
        pm.addPass(mlir::createFinalizeMemRefToLLVMConversionPass());
        // Convert Func to LLVM (always needed).
        pm.addPass(mlir::createConvertFuncToLLVMPass());
        // Convert Arith to LLVM (always needed).
        pm.addPass(mlir::createArithToLLVMConversionPass());
        // Convert CF to LLVM (always needed).
        pm.addPass(mlir::createConvertControlFlowToLLVMPass());
        // Convert Index to LLVM (always needed).
        pm.addPass(mlir::createConvertIndexToLLVMPass());
        // We add this again to catch some unconverted async functions
        pm.addPass(mlir::createConvertFuncToLLVMPass());
        // Convert remaining unrealized_casts (always needed).
        pm.addPass(mlir::createReconcileUnrealizedCastsPass());
      });
}

/**
 * Registers the pipeline for lowering FIFO and CAL dialects to the LLVM
 * dialect. This pipeline assumes all actors are SDF or CSDF actors and
 * statically schedules the execution order.
 */
void registerLowerCalToLLVMWithStaticSchedulePipeline() {
  mlir::PassPipelineRegistration<CalStaticSchedulingPipelineOptions>(
      "lower-cal-to-llvm-with-static-schedule",
      "Pipeline lowering FIFO and CAL dialects to LLVM dialect. Assumes the "
      "actors are SDF and CSDF actors and statically schedules the execution "
      "order.",
      [](mlir::OpPassManager &pm,
         const CalStaticSchedulingPipelineOptions &options) {
        // 1. FIFO/CAL-specific lowering
        if (options.mergeSimpleCalActors)
          pm.addPass(mlir::cal::createMergeSimpleCalActors());

        pm.addPass(mlir::createCanonicalizerPass());
        pm.addPass(mlir::createConvertCalToFuncWithStaticSchedule());

        // We add this pass as we often get functions that are the same but with
        // different names.
        pm.addPass(mlir::func::createDuplicateFunctionEliminationPass());

        pm.addPass(mlir::createLowerCalStateToMemref());
        pm.addPass(mlir::createLowerFifoToMemrefPass());
        pm.addPass(mlir::createDecomposeFifoTuples());
        pm.addPass(mlir::fifo::createLowerFifoPrintToLLVM());

        // 2. We need to add deallocation operations. However the
        // createConvertCalToFuncWithStaticSchedulePass generates CF, not SCF,
        // in the main function. The buffer deallocation pass expects SCF. So
        // we add a conversion here. The conversion gets undone in later passes
        pm.addPass(mlir::createLiftControlFlowToSCFPass());

        // 3. Standard MLIR to LLVM lowering

        if (!options.bypassTensorConversions) { // We add bypass option to
                                                // reduce compilation time
          mlir::bufferization::OneShotBufferizationOptions bufferizeOptions;
          bufferizeOptions.bufferizeFunctionBoundaries = true;
          pm.addPass(mlir::bufferization::createOneShotBufferizePass(
              bufferizeOptions));
          if (!options.disableHoistAllocs)
            pm.addPass(mlir::createHoistAllocsPass());
          pm.addPass(mlir::createCanonicalizerPass());
          pm.addPass(mlir::bufferization::createBufferDeallocationPass());
          pm.addPass(mlir::createCanonicalizerPass());
          pm.addPass(mlir::createConvertLinalgToLoopsPass());
          pm.addPass(mlir::createCanonicalizerPass());
        }

        // Convert SCF to CF (always needed).
        pm.addPass(mlir::createConvertSCFToCFPass());
        // Sprinkle some cleanups.
        pm.addPass(mlir::createCanonicalizerPass());
        pm.addPass(mlir::createCSEPass());

        // Convert Math to LLVM (always needed).
        pm.addNestedPass<mlir::func::FuncOp>(
            mlir::createConvertMathToLLVMPass());
        // Expand complicated MemRef operations before lowering them.
        pm.addPass(mlir::memref::createExpandStridedMetadataPass());
        // The expansion may create affine expressions. Get rid of them.
        pm.addPass(mlir::createLowerAffinePass());
        // Convert MemRef to LLVM (always needed).
        pm.addPass(mlir::createFinalizeMemRefToLLVMConversionPass());
        // Convert Func to LLVM (always needed).
        pm.addPass(mlir::createConvertFuncToLLVMPass());
        // Convert Arith to LLVM (always needed).
        pm.addPass(mlir::createArithToLLVMConversionPass());
        // Convert CF to LLVM (always needed).
        pm.addPass(mlir::createConvertControlFlowToLLVMPass());
        // Convert Index to LLVM (always needed).
        pm.addPass(mlir::createConvertIndexToLLVMPass());
        // Convert remaining unrealized_casts (always needed).
        pm.addPass(mlir::createReconcileUnrealizedCastsPass());
      });
}

/**
 * Builds the pipeline for lowering FIFO and CAL dialects to LLVM with GPU
 * tensors.
 */
void buildLowerCalToLLVMWithGPUTensorsPipeline(
    OpPassManager &pm, const CalToLLVMWithGPUTensorsPipelineOptions &options) {
  // 1. FIFO/CAL-specific lowering
  if (options.mergeSimpleCalActors)
    pm.addPass(mlir::cal::createMergeSimpleCalActors());

  pm.addPass(mlir::cal::insertCalPortPredicates());
  pm.addPass(mlir::cal::convertCalActionsToExecutionBodies());

  pm.addPass(mlir::cal::hoistCalStateOutOfActor());
  pm.addPass(mlir::createCanonicalizerPass());
  pm.addPass(mlir::createConvertCalToFunc());

  // We add this pass as we often get functions that are the same but with
  // different names.
  // pm.addPass(mlir::func::createDuplicateFunctionEliminationPass());

  mlir::LowerCalStateToMemrefOptions stateOptions;
  stateOptions.which_alloc = std::string("GPU");
  pm.addPass(mlir::createLowerCalStateToMemref(stateOptions));

  mlir::LowerFifoToMemrefPassOptions fifoOptions;
  fifoOptions.which_alloc = std::string("GPU");
  pm.addPass(mlir::createLowerFifoToMemrefPass(fifoOptions));
  pm.addPass(mlir::createDecomposeFifoTuples());

  mlir::fifo::LowerFifoPrintToLLVMOptions printOptions;
  printOptions.tensors_on_gpu = true; // We want to lower the prints to GPU
  pm.addPass(mlir::fifo::createLowerFifoPrintToLLVM(printOptions));

  if (!options.disableHoistAllocs)
    pm.addPass(mlir::createHoistAllocsPass());
  pm.addPass(mlir::createDenseConstantsToGpuPass());
  pm.addPass(mlir::createGpuAwareBufferizePass());
  pm.addPass(mlir::createCanonicalizerPass());
  if (!options.disableHoistAllocs)
    pm.addPass(mlir::createHoistAllocsPass());
  pm.addPass(mlir::createCanonicalizerPass());
  // If we hoist the allocs, we need to disable deallocation as this causes
  // the program to crash when deallocating. TODO: Fix this bug
  if (options.disableHoistAllocs)
    pm.addPass(mlir::bufferization::createBufferDeallocationPass());
  pm.addPass(mlir::createCanonicalizerPass());
  pm.addPass(mlir::createConvertLinalgToParallelLoopsPass());
  pm.addPass(mlir::createCanonicalizerPass());
  pm.addPass(mlir::createParallelLoopFusionPass());
  pm.addPass(mlir::createConvertLinalgToLoopsPass());
  llvm::SmallVector<int64_t, 3> tileSizes;
  if (!options.parallelLoopTileSizes.empty()) {
    tileSizes.assign(options.parallelLoopTileSizes.begin(),
                     options.parallelLoopTileSizes.end());
  } else {
    tileSizes = {1024, 1, 1};
  }
  pm.addPass(mlir::createParallelLoopTilingPass(tileSizes, true));

  // 2. GPU-specific lowering
  pm.addPass(mlir::createGpuMapParallelLoopsPass());
  pm.addPass(mlir::createParallelLoopToGpuPass());
  pm.addPass(mlir::createGpuKernelOutliningPass());
  pm.addPass(mlir::createCSEPass());
  if (options.enableAsyncGPUBehaviour) {
    pm.addPass(mlir::createCalPrepareGpuAsyncRegionsPass());
  } else {
    // This pass makes the gpu ops async, but within a very limited scope
    // We do this as the gpu ops need to be async to be compiled.
    pm.addPass(mlir::createGpuAsyncRegionPass());
  }
  pm.addPass(mlir::createConvertSCFToCFPass());

  mlir::gpu::GPUToNVVMPipelineOptions nvvmOptions;
  nvvmOptions.cubinChip = options.cubinChip;
  nvvmOptions.optLevel = options.optLevel;
  mlir::gpu::buildLowerToNVVMPassPipeline(pm, nvvmOptions);
}

/**
 * Registers the pipeline for lowering FIFO and CAL dialects to LLVM with GPU
 * tensors.
 */
void registerLowerCalToLLVMWithGPUTensorsPipeline() {
  mlir::PassPipelineRegistration<CalToLLVMWithGPUTensorsPipelineOptions>(
      "lower-cal-to-llvm-with-gpu-tensors",
      "Pipeline lowering FIFO and CAL dialects to LLVM dialect and executing "
      "tensor operations on NVVM GPUs",
      buildLowerCalToLLVMWithGPUTensorsPipeline);
}

} // namespace mlir::cal